[General]
# iwd manages the wireless interface but does NOT configure IP addresses.
# IP configuration is handled by systemd-networkd.
EnableNetworkConfiguration=false

[Network]
EnableIPv6=true
RoutePriorityOffset=300
