title   ouroborOS 0.4.11 (aarch64)
sort-key 01
architecture aa64
linux   /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-aarch64
initrd  /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-aarch64.img
options archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% console=tty0 console=ttyS0,115200 loglevel=5 systemd.show_status=true ouroborOS.config=/etc/ouroborOS/ouroborOS-config.yaml
