# ouroborOS archiso mkinitcpio config
HOOKS=(base udev archiso archiso_loop_mnt microcode modconf kms keyboard keymap consolefont block btrfs filesystems fsck)
COMPRESSION="zstd"
COMPRESSION_OPTIONS=(-19)
